#!/bin/sh

if [ "$1" = "config" ]; then


        echo 'graph_title kZorp memory usage'
        echo 'graph_args --base 1000'
        echo 'graph_vlabel Slab objects'
        echo 'graph_category Zorp'

        echo "active_objs.label" "Active SLAB entry count"
        echo "num_objs.label" "Total SLAB entry count"
        exit 0
fi

awk '/kzorp_slab/ { print "active_objs.value " $2 "\nnum_objs.value " $3 }' /proc/slabinfo
